#!/usr/bin/env bash
# =============================================================================
# server_info.sh — Server Inspector
# Version: 1.0.0
#
# Comprehensive Linux server diagnostics tool.
# Outputs: OS, hardware, network, virtualization, users, processes, Docker info.
#
# Usage:
#   chmod +x server_info.sh
#   ./server_info.sh              # full report to stdout
#   ./server_info.sh --output /tmp/report.txt  # save report to file
#   ./server_info.sh --no-color   # disable coloured output
#   ./server_info.sh --help       # show help
# =============================================================================

set -euo pipefail

# ----------------------------- GLOBALS ---------------------------------------
VERSION="1.0.0"
OUTPUT_FILE=""
USE_COLOR=true
REPORT_DATE=$(date '+%Y-%m-%d %H:%M:%S %Z')

# ----------------------------- COLOURS ---------------------------------------
setup_colors() {
    if $USE_COLOR && [[ -t 1 ]]; then
        BOLD='\033[1m'
        GREEN='\033[0;32m'
        CYAN='\033[0;36m'
        YELLOW='\033[1;33m'
        RESET='\033[0m'
    else
        BOLD='' GREEN='' CYAN='' YELLOW='' RESET=''
    fi
}

# ----------------------------- HELPERS ---------------------------------------
section() {
    echo ""
    echo -e "${CYAN}${BOLD}━━━━━━━━━━  $1  ━━━━━━━━━━${RESET}"
}

info() { echo -e "  ${GREEN}▸${RESET} $*"; }
warn() { echo -e "  ${YELLOW}⚠${RESET}  $*"; }

command_exists() { command -v "$1" &>/dev/null; }

# ----------------------------- USAGE -----------------------------------------
usage() {
    cat <<EOF
Server Inspector v${VERSION}
Comprehensive Linux server diagnostics tool.

Usage:
  $(basename "$0") [OPTIONS]

Options:
  -o, --output FILE   Save the report to FILE instead of stdout
  --no-color          Disable coloured output
  -v, --version       Show version and exit
  -h, --help          Show this help message and exit

Examples:
  $(basename "$0")
  $(basename "$0") --output /tmp/server_report.txt
  $(basename "$0") --no-color | tee report.txt
EOF
}

# ----------------------------- ARG PARSING -----------------------------------
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -o|--output)   OUTPUT_FILE="${2:-}"; shift 2 ;;
            --no-color)    USE_COLOR=false; shift ;;
            -v|--version)  echo "Server Inspector v${VERSION}"; exit 0 ;;
            -h|--help)     usage; exit 0 ;;
            *)             echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
        esac
    done
}

# ----------------------------- SECTIONS --------------------------------------

header() {
    echo ""
    echo -e "${BOLD}╔══════════════════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}║          SERVER INSPECTION REPORT  v${VERSION}               ║${RESET}"
    echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${RESET}"
    echo -e "  Report generated : ${REPORT_DATE}"
    echo -e "  Generated by     : ${USER:-unknown}@$(hostname)"
}

os_info() {
    section "HOST & OS INFORMATION"
    info "Hostname        : $(hostname -f 2>/dev/null || hostname)"
    if [[ -f /etc/os-release ]]; then
        # shellcheck source=/dev/null
        . /etc/os-release
        info "OS              : ${PRETTY_NAME:-unknown}"
    else
        info "OS              : $(uname -s)"
    fi
    info "Kernel          : $(uname -r)"
    info "Architecture    : $(uname -m)"
    info "Uptime          : $(uptime -p 2>/dev/null || uptime)"
    info "Timezone        : $(timedatectl show --property=Timezone --value 2>/dev/null || date '+%Z')"
}

cpu_info() {
    section "CPU INFORMATION"
    if command_exists lscpu; then
        lscpu | grep -E 'Architecture|Model name|CPU\(s\)|Thread|Core|Socket|Hypervisor|Virtualization' \
              | sed 's/^/  /'
    else
        warn "lscpu not available"
        info "CPU count : $(nproc)"
    fi
}

memory_info() {
    section "MEMORY INFORMATION"
    free -h
}

disk_info() {
    section "DISK INFORMATION"
    echo ""
    echo -e "  ${BOLD}Block devices:${RESET}"
    if command_exists lsblk; then
        lsblk -o NAME,SIZE,TYPE,MOUNTPOINT,MODEL 2>/dev/null | sed 's/^/  /' || true
    fi
    echo ""
    echo -e "  ${BOLD}Filesystem usage:${RESET}"
    df -h --output=source,size,used,avail,pcent,target 2>/dev/null \
        | grep -v tmpfs \
        | sed 's/^/  /' \
        || df -h | sed 's/^/  /'
}

network_info() {
    section "NETWORK INFORMATION"

    echo -e "  ${BOLD}Interfaces & IP addresses:${RESET}"
    if command_exists ip; then
        ip -brief address 2>/dev/null | sed 's/^/  /' \
            || ip addr | sed 's/^/  /'
    elif command_exists ifconfig; then
        ifconfig | sed 's/^/  /'
    else
        warn "No network utility (ip/ifconfig) found"
    fi

    echo ""
    echo -e "  ${BOLD}Routing table:${RESET}"
    if command_exists ip; then
        ip route | sed 's/^/  /'
    fi

    echo ""
    echo -e "  ${BOLD}DNS resolvers:${RESET}"
    if [[ -f /etc/resolv.conf ]]; then
        grep '^nameserver' /etc/resolv.conf | sed 's/^/  /' || info "No nameservers found"
    fi

    echo ""
    echo -e "  ${BOLD}Public IP & provider:${RESET}"
    if command_exists curl; then
        curl -sf --max-time 5 https://ipinfo.io 2>/dev/null | sed 's/^/  /' \
            || warn "Unable to reach ipinfo.io"
    elif command_exists wget; then
        wget -qO- --timeout=5 https://ipinfo.io 2>/dev/null | sed 's/^/  /' \
            || warn "Unable to reach ipinfo.io"
    else
        warn "curl/wget not available — skipping public IP lookup"
    fi
}

virt_info() {
    section "VIRTUALIZATION STATUS"
    if command_exists systemd-detect-virt; then
        virt_type=$(systemd-detect-virt 2>/dev/null || echo "unknown")
        if [[ "$virt_type" == "none" ]]; then
            info "Virtualization  : None (Physical Server)"
        else
            info "Virtualization  : ${virt_type}"
        fi
    else
        warn "systemd-detect-virt not available"
    fi

    if command_exists dmidecode; then
        product=$(sudo dmidecode -s system-product-name 2>/dev/null || echo "unavailable")
        info "Product name    : ${product}"
    fi
}

users_info() {
    section "USERS & SECURITY"
    echo -e "  ${BOLD}Currently logged-in users:${RESET}"
    who | sed 's/^/  /' || info "No users logged in"

    echo ""
    echo -e "  ${BOLD}Last 5 logins:${RESET}"
    last -n 5 2>/dev/null | sed 's/^/  /' || warn "last command unavailable"

    echo ""
    echo -e "  ${BOLD}Users with sudo privileges:${RESET}"
    if command_exists getent; then
        getent group sudo wheel 2>/dev/null | sed 's/^/  /' || info "No sudo/wheel group found"
    fi

    echo ""
    echo -e "  ${BOLD}Accounts with empty passwords:${RESET}"
    if [[ -r /etc/shadow ]]; then
        awk -F: '($2 == "" || $2 == "!!" ) {print $1}' /etc/shadow 2>/dev/null \
            | sed 's/^/  /' \
            || info "None found"
    else
        warn "Cannot read /etc/shadow (run as root for full security audit)"
    fi
}

services_info() {
    section "ACTIVE SERVICES (top 20)"
    if command_exists systemctl; then
        systemctl list-units --type=service --state=running --no-legend 2>/dev/null \
            | head -n 20 \
            | sed 's/^/  /' \
            || warn "systemctl unavailable"
    else
        warn "systemd not available"
        if command_exists service; then
            service --status-all 2>&1 | grep '+ ' | head -n 20 | sed 's/^/  /'
        fi
    fi
}

processes_info() {
    section "TOP PROCESSES"
    echo -e "  ${BOLD}By CPU usage:${RESET}"
    ps aux --sort=-%cpu 2>/dev/null | head -n 11 | sed 's/^/  /'

    echo ""
    echo -e "  ${BOLD}By memory usage:${RESET}"
    ps aux --sort=-%mem 2>/dev/null | head -n 11 | sed 's/^/  /'
}

docker_info() {
    section "DOCKER"
    if command_exists docker; then
        echo -e "  ${BOLD}Docker version:${RESET}"
        docker version --format 'Client: {{.Client.Version}}  Server: {{.Server.Version}}' 2>/dev/null \
            | sed 's/^/  /' \
            || docker --version | sed 's/^/  /'

        echo ""
        echo -e "  ${BOLD}Docker info summary:${RESET}"
        docker info --format \
            'Containers: {{.Containers}} (running: {{.ContainersRunning}})  Images: {{.Images}}' \
            2>/dev/null | sed 's/^/  /' || true

        echo ""
        echo -e "  ${BOLD}All containers:${RESET}"
        docker ps -a 2>/dev/null | sed 's/^/  /' || true
    else
        info "Docker is not installed"
    fi
}

footer() {
    echo ""
    echo -e "${BOLD}╔══════════════════════════════════════════════════════════╗${RESET}"
    echo -e "${BOLD}║                  END OF REPORT                          ║${RESET}"
    echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${RESET}"
    echo ""
}

# ----------------------------- MAIN ------------------------------------------
main() {
    parse_args "$@"
    setup_colors

    if [[ -n "$OUTPUT_FILE" ]]; then
        # Redirect all output to file; disable colour for cleaner text files
        USE_COLOR=false
        setup_colors
        {
            header
            os_info
            cpu_info
            memory_info
            disk_info
            network_info
            virt_info
            users_info
            services_info
            processes_info
            docker_info
            footer
        } > "$OUTPUT_FILE"
        echo "Report saved to: ${OUTPUT_FILE}"
    else
        header
        os_info
        cpu_info
        memory_info
        disk_info
        network_info
        virt_info
        users_info
        services_info
        processes_info
        docker_info
        footer
    fi
}

main "$@"
